theme: minima

title: Luke Raymond's Profile
author: Luke Raymond
email: s2821924@student.rmit.edu.au
description: > # this means to ignore newlines until "baseurl:"
  Hello i'm Luke

# social links
twitter_username: LJR_Designs
github_username:  lukasaurus35

show_excerpts: true # set to false to remove excerpts on the homepage
